package syntatic.analysis;

import lexical.analysis.Scanner;
import lexical.analysis.Token;
import lexical.analysis.TokenKind;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import static lexical.analysis.TokenKind.*;

/**
 * The Syntax analyzer (Parser) takes a string of tokens from the Lexical analyzer (Scanner),
 * and verifies that the string input of tokens can be generated by accordance to the grammar
 * of the source language, returns any syntax error for the source language
 */
public class Parser {
    private final Scanner scanner;
    private Token currentTerminal;
    private static final Logger logger = LogManager.getLogger(Parser.class);

    public Parser(Scanner scanner) {
        System.setProperty("log4j.configurationFile", "src/main/resources/log4j2.properties");
        this.scanner = scanner;
        currentTerminal = scanner.scan();
    }

    public void parseProgram() {
        parseBlock();
        if (currentTerminal.kind != EOT)
            logger.error("Syntax error: Tokens found after end of program");
    }

    /**
     * Check if declaration of a block is valid
     */
    private void parseBlock() {
        accept(DECLARE);
        parseDeclarations();
        accept(DO);
        parseStatements();
    }


    private void parseDeclarations() {
        while (currentTerminal.kind == EOT ||
                currentTerminal.kind == FUNC)
            parseOneDeclaration();
    }


    private void parseOneDeclaration() {
        switch (currentTerminal.kind) {
            case INTEGER:
                accept(INTEGER_LITERAL);
                accept(DECLARE);
                accept(IDENTIFIER);
                accept(SEMICOLON);
                break;
            case BOOLEAN:
                accept(BOOLEAN_LITERAL);
                accept(DECLARE);
                accept(IDENTIFIER);
                accept(SEMICOLON);
                break;

            case FUNC:
                accept(FUNC);
                accept(IDENTIFIER);
                accept(LEFT_PARAM);

                if (currentTerminal.kind == IDENTIFIER)
                    parseIdList();

                accept(RIGHT_PARAM);
                parseBlock();
                accept(RETURN);
                parseExpression();
                accept(SEMICOLON);
                break;

            default:
                logger.error("Syntax error: Variable or function expected");
                break;
        }
    }

    private void parseIdList() {
        accept(IDENTIFIER);

        while (currentTerminal.kind == COMMA) {
            accept(COMMA);
            accept(IDENTIFIER);
        }
    }

    private void parseStatements() {
        while (currentTerminal.kind == IDENTIFIER ||
                currentTerminal.kind == OPERATOR ||
                currentTerminal.kind == INTEGER_LITERAL ||
                currentTerminal.kind == LEFT_PARAM ||
                currentTerminal.kind == IF ||
                currentTerminal.kind == WHILE ||
                currentTerminal.kind == INPUT ||
                currentTerminal.kind == OUTPUT)
            parseOneStatement();
    }

    private void parseOneStatement() {
        switch (currentTerminal.kind) {
            case IDENTIFIER:
            case INTEGER_LITERAL:
            case OPERATOR:
            case LEFT_PARAM:
                parseExpression();
                accept(SEMICOLON);
                break;

            case IF:
                accept(IF);
                parseExpression();
                parseStatements();
                if (currentTerminal.kind == ELSE) {
                    accept(ELSE);
                    parseStatements();
                }

                break;

            case WHILE:
                accept(WHILE);
                parseExpression();
                accept(DO);
                parseStatements();
                accept(SEMICOLON);
                break;

            case INPUT:
                accept(INPUT);
                parseExpression();
                accept(SEMICOLON);
                break;
            case OUTPUT:
                accept(OUTPUT);
                parseExpression();
                accept(SEMICOLON);
                break;

            default:
                logger.error("Syntax error: Error found in statement");
                break;
        }
    }

    private void parseExpression() {
        parsePrimary();
        while (currentTerminal.kind == OPERATOR) {
            accept(OPERATOR);
            parsePrimary();
        }
    }

    private void parsePrimary() {
        switch (currentTerminal.kind) {
            case IDENTIFIER:
                accept(IDENTIFIER);

                if (currentTerminal.kind == LEFT_PARAM) {
                    accept(LEFT_PARAM);

                    if (currentTerminal.kind == IDENTIFIER ||
                            currentTerminal.kind == INTEGER_LITERAL ||
                            currentTerminal.kind == OPERATOR ||
                            currentTerminal.kind == LEFT_PARAM)
                        parseExpressionList();


                    accept(RIGHT_PARAM);
                }
                break;

            case INTEGER_LITERAL:
                accept(INTEGER_LITERAL);
                break;
            case BOOLEAN_LITERAL:
                accept(BOOLEAN_LITERAL);
                break;

            case OPERATOR:
                accept(OPERATOR);
                parsePrimary();
                break;

            case LEFT_PARAM:
                accept(LEFT_PARAM);
                parseExpression();
                accept(RIGHT_PARAM);
                break;

            default:
                logger.error("Syntax error: Error occurred in while primary parsing");
                break;
        }
    }


    private void parseExpressionList() {
        parseExpression();
        while (currentTerminal.kind == COMMA) {
            accept(COMMA);
            parseExpression();
        }
    }

    /**
     * accept checks if the token given matches the token expected,
     * if not reports a syntactic error
     * @param expected token
     */
    private void accept(TokenKind expected) {
        if (currentTerminal.kind == expected) {
            currentTerminal = scanner.scan();
        } else {
            logger.error(String.format("Syntax error: Expected token of kind [%s]", expected));
        }
    }
}
